DROP DATABASE IF EXISTS alex_gracia;
CREATE DATABASE alex_gracia;
USE alex_gracia;
-- 0
CREATE TABLE CLIENTES
(
ID_CLIENTES INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
CODIGO_CLIENTES VARCHAR(100) default 'sin codigo',
NOMBRE VARCHAR(50) NOT NULL,
APELLIDOS VARCHAR(100) default 'desconocidos',
DNI VARCHAR(9) NOT NULL UNIQUE,
TELEFONO int default 0,
FECHA_NACIMIENTO DATE CHECK(FECHA_NACIMIENTO<CURRENT_DATE),
FECHA_CARNET DATE CHECK(FECHA_CARNET<CURRENT_DATE),
DIRECCION VARCHAR(200) default 'desconocida'
)ENGINE = InnoDB;
-- 1
CREATE TABLE VEHICULOS
(
ID_VEHICULOS INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
NUMERO_CHASIS VARCHAR(17) default 'sin chasis',
MATRICULA VARCHAR(100) NOT NULL unique,
MARCA VARCHAR(100) default 'desconocida',
MODELO VARCHAR(100) default 'desconocido',
POTENCIA int default 0,
ANO_FABRICACION DATE CHECK(ANO_FABRICACION<CURRENT_DATE),
COLOR enum('','Metalizado','Mate'),
NUMERO_PUERTAS INT(1) DEFAULT 0,
KILOMETROS INT DEFAULT 0
)ENGINE = InnoDB;
-- 2
CREATE TABLE EXTRAS
(
ID_EXTRAS INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
ANO_FABRICACION DATE CHECK(ANO_FABRICACION<CURRENT_DATE),
MARCA VARCHAR(100) default 'desconocida',
NOMBRE VARCHAR(100) NOT NULL,
MODELO VARCHAR(100) NOT NULL,
DESCRIPCION VARCHAR(250) default 'sin descripcion',
LUGAR_ORIGEN VARCHAR(100) default 'desconocido',
DIMENSIONES VARCHAR(100) NOT NULL,
FABRICANTE VARCHAR(100) default 'desconocido'
)ENGINE = InnoDB;
-- 3
CREATE TABLE PIEZAS
(
ID_PIEZAS INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
CODIGO_PIEZAS INT DEFAULT 0,
NOMBRE VARCHAR(100) NOT NULL,
DESCRIPCION VARCHAR(250),
CANTIDAD INT DEFAULT 0,
PRECIO INT DEFAULT 0,
LUGAR_ORIGEN VARCHAR(200) NOT NULL,
FECHA_SOLICITUD DATE,
MARCA VARCHAR(100)
)ENGINE = InnoDB;
-- 4
CREATE TABLE PROVEEDORES
(
ID_PROVEEDORES INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(100) NOT NULL,
TELEFONO int default 0,-- importante
CORREO_ELECTRONICO VARCHAR(100),
FECHA_NACIMIENTO DATE CHECK(FECHA_NACIMIENTO<CURRENT_DATE),
DIRECCION VARCHAR(200),
FACILIDAD_PAGO enum('','Con_plazos','Sin_plazos'),
NOMBRE_EMPRESA VARCHAR(100) NOT NULL,
DNI VARCHAR(9) NOT NULL UNIQUE
)ENGINE = InnoDB;
-- 5
CREATE TABLE TALLERES
(
ID_TALLERES INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(100) NOT NULL,
DIRECCION VARCHAR(200) NOT NULL,
TELEFONO int default 0,
FECHA_INICIO DATE CHECK(FECHA_INICIO<CURRENT_DATE),
NOMBRE_JEFE VARCHAR(100),
CIF_EMPRESA VARCHAR(20) NOT NULL UNIQUE,
NUMERO_TRABAJADORES INT DEFAULT 0,
CANTIDAD_REPARACIONES INT DEFAULT 0
)ENGINE = InnoDB;
-- 6
CREATE TABLE POLIZAS
(
ID_POLIZAS INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
NUMERO INT DEFAULT 0,
TIPO enum('','A_todo_riesgo', 'A_terceros'),
IMPORTE INT DEFAULT 0,
ESTADO enum('','Alta', 'Suspension', 'Baja'),
FECHA_INICIO DATE CHECK(FECHA_INICIO<CURRENT_DATE),
CANTIDAD_CONDUCTORES INT DEFAULT 0,
ANTIGUEDAD_CONDUCCION DATE CHECK(ANTIGUEDAD_CONDUCCION<CURRENT_DATE),
FECHA_FIN DATE NOT NULL,
ID_CLIENTE INT UNSIGNED NOT NULL,
INDEX (ID_CLIENTE),
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTES),
ID_VEHICULO INT UNSIGNED NOT NULL,
INDEX (ID_VEHICULO),
FOREIGN KEY (ID_VEHICULO) REFERENCES VEHICULOS (ID_VEHICULOS)
)ENGINE = InnoDB;
-- 7
CREATE TABLE SINIESTROS
(
ID_SINIESTROS INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
DATOS_POLIZA VARCHAR(200),
IMPORTE_REPARACION REAL DEFAULT 0,
DATOS_CLIENTE VARCHAR(200),
FECHA_REPARACION DATE,
DATOS_TALLER VARCHAR(200),
FECHA_SINIESTRO DATETIME,
CANTIDAD_VEHICULOS_IMPLICADOS INT DEFAULT 1,
ID_CLIENTE INT UNSIGNED NOT NULL,
INDEX (ID_CLIENTE),
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTES),
ID_TALLER INT UNSIGNED NOT NULL,
INDEX (ID_TALLER),
FOREIGN KEY (ID_TALLER) REFERENCES TALLERES (ID_TALLERES),
CLIENTES_HERIDOS INT DEFAULT 0
)ENGINE = InnoDB;
-- 8
CREATE TABLE EXTRAS_VEHICULOS
(
ID_EXTRA INT UNSIGNED NOT NULL,
INDEX (ID_EXTRA),
FOREIGN KEY (ID_EXTRA) REFERENCES EXTRAS (ID_EXTRAS),
ID_VEHICULO INT UNSIGNED NOT NULL,
INDEX (ID_VEHICULO),
FOREIGN KEY (ID_VEHICULO) REFERENCES VEHICULOS (ID_VEHICULOS),
PRIMARY KEY(ID_EXTRA,ID_VEHICULO)
)ENGINE = InnoDB;
-- 9
CREATE TABLE PIEZAS_TALLERES
(
ID_PIEZA INT UNSIGNED NOT NULL,
INDEX (ID_PIEZA),
FOREIGN KEY (ID_PIEZA) REFERENCES PIEZAS (ID_PIEZAS),
ID_TALLER INT UNSIGNED NOT NULL,
INDEX (ID_TALLER),
FOREIGN KEY (ID_TALLER) REFERENCES TALLERES (ID_TALLERES),
PRIMARY KEY(ID_PIEZA,ID_TALLER)
)ENGINE = InnoDB;
-- 10
CREATE TABLE PIEZAS_PROVEEDORES
(
ID_PIEZA INT UNSIGNED NOT NULL,
INDEX (ID_PIEZA),
FOREIGN KEY (ID_PIEZA) REFERENCES PIEZAS (ID_PIEZAS),
ID_PROVEEDOR INT UNSIGNED NOT NULL,
INDEX (ID_PROVEEDOR),
FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDORES (ID_PROVEEDORES),
PRIMARY KEY(ID_PIEZA,ID_PROVEEDOR)
)ENGINE = InnoDB;
-- 11 ---
create table users(
	id int unsigned primary key auto_increment,
	login varchar(20) not null unique,
	password varchar(50) not null,
	rango enum('user','admin','tecnic')
) ENGINE=InnoDB;

-- Insertar usuario
insert into users (login, password, rango) values ('user', '', 'user');

-- Insertar admin
insert into users (login, password, rango) values ('admin', 'admin', 'admin');

-- Insertar tecnic
insert into users (login, password, rango) values ('tecnic', 'tecnic', 'tecnic');