package org.alex.accesodatos.hibernate;

// Generated 17-jun-2014 12:41:48 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Extras generated by hbm2java
 */
@Entity
@Table(name = "extras", catalog = "alex_gracia")
public class Extras implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private Integer idExtras;
	private Date anoFabricacion;
	private String marca;
	private String nombre;
	private String modelo;
	private String descripcion;
	private String lugarOrigen;
	private String dimensiones;
	private String fabricante;
	private Set<Vehiculos> vehiculoses = new HashSet<Vehiculos>(0);

	public Extras() {
	}

	public Extras(String nombre, String modelo, String dimensiones) {
		this.nombre = nombre;
		this.modelo = modelo;
		this.dimensiones = dimensiones;
	}

	public Extras(Date anoFabricacion, String marca, String nombre,
			String modelo, String descripcion, String lugarOrigen,
			String dimensiones, String fabricante, Set<Vehiculos> vehiculoses) {
		this.anoFabricacion = anoFabricacion;
		this.marca = marca;
		this.nombre = nombre;
		this.modelo = modelo;
		this.descripcion = descripcion;
		this.lugarOrigen = lugarOrigen;
		this.dimensiones = dimensiones;
		this.fabricante = fabricante;
		this.vehiculoses = vehiculoses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID_EXTRAS", unique = true, nullable = false)
	public Integer getIdExtras() {
		return this.idExtras;
	}

	public void setIdExtras(Integer idExtras) {
		this.idExtras = idExtras;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ANO_FABRICACION", length = 10)
	public Date getAnoFabricacion() {
		return this.anoFabricacion;
	}

	public void setAnoFabricacion(Date anoFabricacion) {
		this.anoFabricacion = anoFabricacion;
	}

	@Column(name = "MARCA", length = 100)
	public String getMarca() {
		return this.marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

	@Column(name = "NOMBRE", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "MODELO", nullable = false, length = 100)
	public String getModelo() {
		return this.modelo;
	}

	public void setModelo(String modelo) {
		this.modelo = modelo;
	}

	@Column(name = "DESCRIPCION", length = 250)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "LUGAR_ORIGEN", length = 100)
	public String getLugarOrigen() {
		return this.lugarOrigen;
	}

	public void setLugarOrigen(String lugarOrigen) {
		this.lugarOrigen = lugarOrigen;
	}

	@Column(name = "DIMENSIONES", nullable = false, length = 100)
	public String getDimensiones() {
		return this.dimensiones;
	}

	public void setDimensiones(String dimensiones) {
		this.dimensiones = dimensiones;
	}

	@Column(name = "FABRICANTE", length = 100)
	public String getFabricante() {
		return this.fabricante;
	}

	public void setFabricante(String fabricante) {
		this.fabricante = fabricante;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "extras_vehiculos", catalog = "alex_gracia", joinColumns = { @JoinColumn(name = "ID_EXTRA", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "ID_VEHICULO", nullable = false, updatable = false) })
	public Set<Vehiculos> getVehiculoses() {
		return this.vehiculoses;
	}

	public void setVehiculoses(Set<Vehiculos> vehiculoses) {
		this.vehiculoses = vehiculoses;
	}

}
