package org.alex.accesodatos.hibernate;

// Generated 28-jun-2014 19:43:06 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Polizas generated by hbm2java
 */
@Entity
@Table(name = "polizas", catalog = "alex_gracia")
public class Polizas implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer idPolizas, numero, importe, cantidadConductores;
	private Vehiculos vehiculos;
	private Clientes clientes;
	private String tipo, estado;
	private Date fechaInicio, antiguedadConduccion, fechaFin;

	public Polizas() {
	}

	public Polizas(Vehiculos vehiculos, Clientes clientes, Date fechaFin) {
		this.vehiculos = vehiculos;
		this.clientes = clientes;
		this.fechaFin = fechaFin;
	}

	public Polizas(Vehiculos vehiculos, Clientes clientes, Integer numero,
			String tipo, Integer importe, String estado, Date fechaInicio,
			Integer cantidadConductores, Date antiguedadConduccion,
			Date fechaFin) {
		this.vehiculos = vehiculos;
		this.clientes = clientes;
		this.numero = numero;
		this.tipo = tipo;
		this.importe = importe;
		this.estado = estado;
		this.fechaInicio = fechaInicio;
		this.cantidadConductores = cantidadConductores;
		this.antiguedadConduccion = antiguedadConduccion;
		this.fechaFin = fechaFin;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID_POLIZAS", unique = true, nullable = false)
	public Integer getIdPolizas() {
		return this.idPolizas;
	}

	public void setIdPolizas(Integer idPolizas) {
		this.idPolizas = idPolizas;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_VEHICULO", nullable = false)
	public Vehiculos getVehiculos() {
		return this.vehiculos;
	}

	public void setVehiculos(Vehiculos vehiculos) {
		this.vehiculos = vehiculos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CLIENTE", nullable = false)
	public Clientes getClientes() {
		return this.clientes;
	}

	public void setClientes(Clientes clientes) {
		this.clientes = clientes;
	}

	@Column(name = "NUMERO")
	public Integer getNumero() {
		return this.numero;
	}

	public void setNumero(Integer numero) {
		this.numero = numero;
	}

	@Column(name = "TIPO", length = 13)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "IMPORTE")
	public Integer getImporte() {
		return this.importe;
	}

	public void setImporte(Integer importe) {
		this.importe = importe;
	}

	@Column(name = "ESTADO", length = 10)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_INICIO", length = 10)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Column(name = "CANTIDAD_CONDUCTORES")
	public Integer getCantidadConductores() {
		return this.cantidadConductores;
	}

	public void setCantidadConductores(Integer cantidadConductores) {
		this.cantidadConductores = cantidadConductores;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ANTIGUEDAD_CONDUCCION", length = 10)
	public Date getAntiguedadConduccion() {
		return this.antiguedadConduccion;
	}

	public void setAntiguedadConduccion(Date antiguedadConduccion) {
		this.antiguedadConduccion = antiguedadConduccion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_FIN", nullable = false, length = 10)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

}
