package org.alex.accesodatos.hibernate;

// Generated 28-jun-2014 19:43:06 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Proveedores generated by hbm2java
 */
@Entity
@Table(name = "proveedores", catalog = "alex_gracia", uniqueConstraints = @UniqueConstraint(columnNames = "DNI"))
public class Proveedores implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer idProveedores, telefono;
	private String nombre, correoElectronico, direccion, facilidadPago,
			nombreEmpresa, dni;
	private Date fechaNacimiento;
	private Set<Piezas> piezases = new HashSet<Piezas>(0);

	public Proveedores() {
	}

	public Proveedores(String nombre, String nombreEmpresa, String dni) {
		this.nombre = nombre;
		this.nombreEmpresa = nombreEmpresa;
		this.dni = dni;
	}

	public Proveedores(String nombre, Integer telefono,
			String correoElectronico, Date fechaNacimiento, String direccion,
			String facilidadPago, String nombreEmpresa, String dni,
			Set<Piezas> piezases) {
		this.nombre = nombre;
		this.telefono = telefono;
		this.correoElectronico = correoElectronico;
		this.fechaNacimiento = fechaNacimiento;
		this.direccion = direccion;
		this.facilidadPago = facilidadPago;
		this.nombreEmpresa = nombreEmpresa;
		this.dni = dni;
		this.piezases = piezases;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID_PROVEEDORES", unique = true, nullable = false)
	public Integer getIdProveedores() {
		return this.idProveedores;
	}

	public void setIdProveedores(Integer idProveedores) {
		this.idProveedores = idProveedores;
	}

	@Column(name = "NOMBRE", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "TELEFONO")
	public Integer getTelefono() {
		return this.telefono;
	}

	public void setTelefono(Integer telefono) {
		this.telefono = telefono;
	}

	@Column(name = "CORREO_ELECTRONICO", length = 100)
	public String getCorreoElectronico() {
		return this.correoElectronico;
	}

	public void setCorreoElectronico(String correoElectronico) {
		this.correoElectronico = correoElectronico;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_NACIMIENTO", length = 10)
	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	@Column(name = "DIRECCION", length = 200)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "FACILIDAD_PAGO", length = 10)
	public String getFacilidadPago() {
		return this.facilidadPago;
	}

	public void setFacilidadPago(String facilidadPago) {
		this.facilidadPago = facilidadPago;
	}

	@Column(name = "NOMBRE_EMPRESA", nullable = false, length = 100)
	public String getNombreEmpresa() {
		return this.nombreEmpresa;
	}

	public void setNombreEmpresa(String nombreEmpresa) {
		this.nombreEmpresa = nombreEmpresa;
	}

	@Column(name = "DNI", unique = true, nullable = false, length = 9)
	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "piezas_proveedores", catalog = "alex_gracia", joinColumns = { @JoinColumn(name = "ID_PROVEEDOR", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "ID_PIEZA", nullable = false, updatable = false) })
	public Set<Piezas> getPiezases() {
		return this.piezases;
	}

	public void setPiezases(Set<Piezas> piezases) {
		this.piezases = piezases;
	}

}
