package org.alex.accesodatos.hibernate;

// Generated 09-jun-2014 18:35:01 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Siniestros generated by hbm2java
 */
@Entity
@Table(name = "siniestros", catalog = "alex_gracia")
public class Siniestros implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer idSiniestros;
	private Clientes clientes;
	private Talleres talleres;
	private String datosPoliza;
	private Double importeReparacion;
	private String datosCliente;
	private Date fechaReparacion;
	private String datosTaller;
	private Date fechaSiniestro;
	private Integer cantidadVehiculosImplicados;
	private Integer clientesHeridos;

	public Siniestros() {
	}

	public Siniestros(Clientes clientes, Talleres talleres, String datosPoliza,
			String datosCliente, Date fechaReparacion, String datosTaller,
			Date fechaSiniestro) {
		this.clientes = clientes;
		this.talleres = talleres;
		this.datosPoliza = datosPoliza;
		this.datosCliente = datosCliente;
		this.fechaReparacion = fechaReparacion;
		this.datosTaller = datosTaller;
		this.fechaSiniestro = fechaSiniestro;
	}

	public Siniestros(Clientes clientes, Talleres talleres, String datosPoliza,
			Double importeReparacion, String datosCliente,
			Date fechaReparacion, String datosTaller, Date fechaSiniestro,
			Integer cantidadVehiculosImplicados, Integer clientesHeridos) {
		this.clientes = clientes;
		this.talleres = talleres;
		this.datosPoliza = datosPoliza;
		this.importeReparacion = importeReparacion;
		this.datosCliente = datosCliente;
		this.fechaReparacion = fechaReparacion;
		this.datosTaller = datosTaller;
		this.fechaSiniestro = fechaSiniestro;
		this.cantidadVehiculosImplicados = cantidadVehiculosImplicados;
		this.clientesHeridos = clientesHeridos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID_SINIESTROS", unique = true, nullable = false)
	public Integer getIdSiniestros() {
		return this.idSiniestros;
	}

	public void setIdSiniestros(Integer idSiniestros) {
		this.idSiniestros = idSiniestros;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CLIENTE", nullable = false)
	public Clientes getClientes() {
		return this.clientes;
	}

	public void setClientes(Clientes clientes) {
		this.clientes = clientes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_TALLER", nullable = false)
	public Talleres getTalleres() {
		return this.talleres;
	}

	public void setTalleres(Talleres talleres) {
		this.talleres = talleres;
	}

	@Column(name = "DATOS_POLIZA", nullable = false, length = 200)
	public String getDatosPoliza() {
		return this.datosPoliza;
	}

	public void setDatosPoliza(String datosPoliza) {
		this.datosPoliza = datosPoliza;
	}

	@Column(name = "IMPORTE_REPARACION", precision = 22, scale = 0)
	public Double getImporteReparacion() {
		return this.importeReparacion;
	}

	public void setImporteReparacion(Double importeReparacion) {
		this.importeReparacion = importeReparacion;
	}

	@Column(name = "DATOS_CLIENTE", nullable = false, length = 200)
	public String getDatosCliente() {
		return this.datosCliente;
	}

	public void setDatosCliente(String datosCliente) {
		this.datosCliente = datosCliente;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_REPARACION", nullable = false, length = 10)
	public Date getFechaReparacion() {
		return this.fechaReparacion;
	}

	public void setFechaReparacion(Date fechaReparacion) {
		this.fechaReparacion = fechaReparacion;
	}

	@Column(name = "DATOS_TALLER", nullable = false, length = 200)
	public String getDatosTaller() {
		return this.datosTaller;
	}

	public void setDatosTaller(String datosTaller) {
		this.datosTaller = datosTaller;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA_SINIESTRO", nullable = false, length = 19)
	public Date getFechaSiniestro() {
		return this.fechaSiniestro;
	}

	public void setFechaSiniestro(Date fechaSiniestro) {
		this.fechaSiniestro = fechaSiniestro;
	}

	@Column(name = "CANTIDAD_VEHICULOS_IMPLICADOS")
	public Integer getCantidadVehiculosImplicados() {
		return this.cantidadVehiculosImplicados;
	}

	public void setCantidadVehiculosImplicados(
			Integer cantidadVehiculosImplicados) {
		this.cantidadVehiculosImplicados = cantidadVehiculosImplicados;
	}

	@Column(name = "CLIENTES_HERIDOS")
	public Integer getClientesHeridos() {
		return this.clientesHeridos;
	}

	public void setClientesHeridos(Integer clientesHeridos) {
		this.clientesHeridos = clientesHeridos;
	}

}
