package org.alex.accesodatos.hibernate;

// Generated 28-jun-2014 19:43:06 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Talleres generated by hbm2java
 */
@Entity
@Table(name = "talleres", catalog = "alex_gracia", uniqueConstraints = @UniqueConstraint(columnNames = "CIF_EMPRESA"))
public class Talleres implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer idTalleres, telefono, numeroTrabajadores,
			cantidadReparaciones;
	private String nombre, direccion, nombreJefe, cifEmpresa;
	private Date fechaInicio;
	private Set<Piezas> piezases = new HashSet<Piezas>(0);
	private Set<Siniestros> siniestroses = new HashSet<Siniestros>(0);

	public Talleres() {
	}

	public Talleres(String nombre, String direccion, String cifEmpresa) {
		this.nombre = nombre;
		this.direccion = direccion;
		this.cifEmpresa = cifEmpresa;
	}

	public Talleres(String nombre, String direccion, Integer telefono,
			Date fechaInicio, String nombreJefe, String cifEmpresa,
			Integer numeroTrabajadores, Integer cantidadReparaciones,
			Set<Piezas> piezases, Set<Siniestros> siniestroses) {
		this.nombre = nombre;
		this.direccion = direccion;
		this.telefono = telefono;
		this.fechaInicio = fechaInicio;
		this.nombreJefe = nombreJefe;
		this.cifEmpresa = cifEmpresa;
		this.numeroTrabajadores = numeroTrabajadores;
		this.cantidadReparaciones = cantidadReparaciones;
		this.piezases = piezases;
		this.siniestroses = siniestroses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID_TALLERES", unique = true, nullable = false)
	public Integer getIdTalleres() {
		return this.idTalleres;
	}

	public void setIdTalleres(Integer idTalleres) {
		this.idTalleres = idTalleres;
	}

	@Column(name = "NOMBRE", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "DIRECCION", nullable = false, length = 200)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "TELEFONO")
	public Integer getTelefono() {
		return this.telefono;
	}

	public void setTelefono(Integer telefono) {
		this.telefono = telefono;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_INICIO", length = 10)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Column(name = "NOMBRE_JEFE", length = 100)
	public String getNombreJefe() {
		return this.nombreJefe;
	}

	public void setNombreJefe(String nombreJefe) {
		this.nombreJefe = nombreJefe;
	}

	@Column(name = "CIF_EMPRESA", unique = true, nullable = false, length = 20)
	public String getCifEmpresa() {
		return this.cifEmpresa;
	}

	public void setCifEmpresa(String cifEmpresa) {
		this.cifEmpresa = cifEmpresa;
	}

	@Column(name = "NUMERO_TRABAJADORES")
	public Integer getNumeroTrabajadores() {
		return this.numeroTrabajadores;
	}

	public void setNumeroTrabajadores(Integer numeroTrabajadores) {
		this.numeroTrabajadores = numeroTrabajadores;
	}

	@Column(name = "CANTIDAD_REPARACIONES")
	public Integer getCantidadReparaciones() {
		return this.cantidadReparaciones;
	}

	public void setCantidadReparaciones(Integer cantidadReparaciones) {
		this.cantidadReparaciones = cantidadReparaciones;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "piezas_talleres", catalog = "alex_gracia", joinColumns = { @JoinColumn(name = "ID_TALLER", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "ID_PIEZA", nullable = false, updatable = false) })
	public Set<Piezas> getPiezases() {
		return this.piezases;
	}

	public void setPiezases(Set<Piezas> piezases) {
		this.piezases = piezases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "talleres")
	public Set<Siniestros> getSiniestroses() {
		return this.siniestroses;
	}

	public void setSiniestroses(Set<Siniestros> siniestroses) {
		this.siniestroses = siniestroses;
	}

}
